### ISSUE TITLE
@SetSystemProperty not working

### ISSUE THREAD

**Issue by william-ferguson-au** [junit-pioneer/junit-pioneer#575]
This is my test:
```
    @Test
    @SetSystemProperty(key = "java.locale.providers", value = "HOST,JRE,SPI")
    public void testSetSystemProperty() {
        // Ensure that you run this test case with -Djava.locale.providers=HOST,JRE,SPI
        System.out.println("java.locale.providers=" + System.getProperty("java.locale.providers"));
        Assert.assertEquals("HOST,JRE,SPI", System.getProperty("java.locale.providers"));
    }
```

This is the result I'm getting:
```
java.locale.providers=null

java.lang.AssertionError: 
Expected :HOST,JRE,SPI
Actual   :null
```

Am I expecting too much from junit-pioneer, or should this test case work?
If it should work, what am I doing wrong?

**Comment by Michael1993** [comment]
Could not reproduce. I don't mean to insult you but is it possible you have a typo somewhere? That'd be the simplest explanation.

**Comment by william-ferguson-au** [comment]
That's a copy and paste.

Running on Java8.

**Comment by Michael1993** [comment]
I copy-pasted this and it works for me... Do you use this system property in other tests? My next best guess is that you are running your tests in parallel and another test modifies/clears this property.

**Comment by william-ferguson-au** [comment]
No it was simpler (and dumber) than that.
That build module was sucking in Junit4.

It works as advertised - thanks for your help.

**Comment by william-ferguson-au** [comment]
OK, ensuring we are using Junit5 appears to make @setSystemProperty work.
But it doesn't seem to really be setting the system property because it exhibits different behaviour that when I run the test and set the system property on the command line.

```
    @Test
    @SetSystemProperty(key = "java.locale.providers", value = "HOST,JRE,SPI") // See https://stackoverflow.com/a/59635733/493682
    public void testParseHOST() throws ParseException {
        // Ensure that you run this test case with -Djava.locale.providers=HOST,JRE,SPI
        System.out.println("java.locale.providers=" + System.getProperty("java.locale.providers"));
        Assertions.assertEquals("HOST,JRE,SPI", System.getProperty("java.locale.providers"));

        // TODO Even though the system property seems to have changed here it is not providing the same behaviour
        //  as when I invoke with with -Djava.locale.providers=HOST,JRE.SPI

        final StdDateFormat stdDateFormat = new StdDateFormat(); // from com.fasterxml.jackson.core:jackson-databind:2.4.0

        // #parse throws an Exception when run with
        // java.locale.providers=HOST,JRE,SPI
        //
        // java.text.ParseException: Can not parse date "2018-07-22T06:20:30.123": not compatible with any of standard forms ("yyyy-MM-dd'T'HH:mm:ss.SSSZ", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", "EEE, dd MMM yyyy HH:mm:ss zzz", "yyyy-MM-dd")
        // at com.fasterxml.jackson.databind.util.StdDateFormat.parse(StdDateFormat.java:274)
        // at com.mypackage.DateFormatTest.testParseHOST(DateFormatTest.java:55)

        // #parse succeeds when run just @SetSystemProperty (and with no command line system property)
        // when it should not.

        Assertions.assertEquals(date, stdDateFormat.parse("2018-07-22T06:20:30.123"));
    }

```

**Comment by Michael1993** [comment]
Hm. How do you set your system property on the command line? Could you paste that here as well?

**Comment by william-ferguson-au** [comment]
I'm running the test in IntelliJ
But essentially passing "-Djava.locale.providers=HOST,JRE,SPI" in the run configuration

<img width="905" alt="image" src="https://user-images.githubusercontent.com/670599/148563406-6b37e70e-9ef9-4f2c-a52c-24b13690d661.png">

**Comment by beatngu13** [comment]
Hi @william-ferguson-au!

I've created this test:

```java
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class Issue575 {

	static final String LOCALE_PROVIDERS_PROPERTY_KEY = "java.locale.providers";
	static final String LOCALE_PROVIDERS_PROPERTY_VALUE = "HOST,JRE,SPI";

	static final String DATE_STRING = "2018-07-22T06:20:30.123";
	static final Date EXPECTED_DATE = new Date(1532240430123L);

	@Order(1)
	@Test
	void test_null() throws Exception {
		assertNull(System.getProperty(LOCALE_PROVIDERS_PROPERTY_KEY));

		final StdDateFormat stdDateFormat = new StdDateFormat();
		Date date = stdDateFormat.parse(DATE_STRING);

		assertEquals(EXPECTED_DATE, date);
	}

	@Order(2)
	@Test
	void test_system() throws Exception {
		System.setProperty(LOCALE_PROVIDERS_PROPERTY_KEY, LOCALE_PROVIDERS_PROPERTY_VALUE);

		final StdDateFormat stdDateFormat = new StdDateFormat();
		Date date = stdDateFormat.parse(DATE_STRING);

		assertEquals(EXPECTED_DATE, date);

		System.clearProperty(LOCALE_PROVIDERS_PROPERTY_KEY);
	}

	@Order(3)
	@Test
	@SetSystemProperty(key = LOCALE_PROVIDERS_PROPERTY_KEY, value = LOCALE_PROVIDERS_PROPERTY_VALUE)
	void test_pioneer() throws Exception {
		assertEquals(LOCALE_PROVIDERS_PROPERTY_VALUE, System.getProperty(LOCALE_PROVIDERS_PROPERTY_KEY));

		final StdDateFormat stdDateFormat = new StdDateFormat();
		Date date = stdDateFormat.parse(DATE_STRING);

		assertEquals(EXPECTED_DATE, date);
	}

}
```

POM:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.github.beatngu13</groupId>
	<artifactId>playground</artifactId>
	<version>0.1.0-SNAPSHOT</version>

	<properties>
		<encoding>UTF-8</encoding>
		<project.build.sourceEncoding>${encoding}</project.build.sourceEncoding>
		<project.resources.sourceEncoding>${encoding}</project.resources.sourceEncoding>
		<java.version>17</java.version>
		<junit.jupiter.version>5.8.2</junit.jupiter.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.junit</groupId>
				<artifactId>junit-bom</artifactId>
				<version>${junit.jupiter.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.4.0</version>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.junit-pioneer</groupId>
			<artifactId>junit-pioneer</artifactId>
			<version>1.5.0</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<release>${java.version}</release>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.22.2</version>
			</plugin>
		</plugins>
	</build>
</project>
```

All are green. This is also the case when I remove `assertNull` from `test_null` and pass in `-Djava.locale.providers=HOST,JRE,SPI`.

Could you please provide an [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?

**Comment by Michael1993** [comment]
I tested your configuration in IntelliJ and it works for me. Do you use `@ClearSystemProperty` anywhere?

**Comment by william-ferguson-au** [comment]
Thanks for sticking with this.

The sample you provided above works fine when I run the tests in IntelliJ against Java16.

But I'm running against Java 8.
When I run against Java 8 (in IntelliJ) and set "-Djava.locale.providers=HOST,JRE,SPI" then all 3 tests fail.

NB I needed to mod it slightly to run against Java8.
See https://github.com/william-ferguson-au/pioneer-test

This is the output
```
java.version=1.8.0_281
java.locale.providers=null

java.text.ParseException: Can not parse date "2018-07-22T06:20:30.123": not compatible with any of standard forms ("yyyy-MM-dd'T'HH:mm:ss.SSSZ", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", "EEE, dd MMM yyyy HH:mm:ss zzz", "yyyy-MM-dd")

	at com.fasterxml.jackson.databind.util.StdDateFormat.parse(StdDateFormat.java:274)
	at mypackage.Issue575Test.test_null(Issue575Test.java:34)

java.locale.providers=HOST,JRE,SPI

java.text.ParseException: Can not parse date "2018-07-22T06:20:30.123": not compatible with any of standard forms ("yyyy-MM-dd'T'HH:mm:ss.SSSZ", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", "EEE, dd MMM yyyy HH:mm:ss zzz", "yyyy-MM-dd")

	at com.fasterxml.jackson.databind.util.StdDateFormat.parse(StdDateFormat.java:274)
	at mypackage.Issue575Test.test_system(Issue575Test.java:46)

java.locale.providers=HOST,JRE,SPI

java.text.ParseException: Can not parse date "2018-07-22T06:20:30.123": not compatible with any of standard forms ("yyyy-MM-dd'T'HH:mm:ss.SSSZ", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", "EEE, dd MMM yyyy HH:mm:ss zzz", "yyyy-MM-dd")

	at com.fasterxml.jackson.databind.util.StdDateFormat.parse(StdDateFormat.java:274)
	at mypackage.Issue575Test.test_pioneer(Issue575Test.java:61)


Process finished with exit code -1
```

But if I run the test on the command line using "mvn -Djava.locale.providers=HOST,JRE,SPI test" all3 tests pass.

**Comment by beatngu13** [comment]
@william-ferguson-au thx for setting up that example! 👍

Have you tried invoking `System.setProperty(String, String)` before and/or within the test? Because this is essentially what the extension does.

**Comment by william-ferguson-au** [comment]
Yes I have.

Doing so changes the value of the property according to ```System.getProperty(String)```  but doesn't change the behaviour.
I suspect this is because StdDateFormat or something it relies on is being prepped prior to that.

**Comment by william-ferguson-au** [comment]
Now that I understand how junit-pioneer works, I'm happy to close this.
I don't think junit-pioneer is going to be able to help us test this.

**Comment by VinceGall** [comment]
> Now that I understand how junit-pioneer works, I'm happy to close this. I don't think junit-pioneer is going to be able to help us test this.

Hi William,
Did you manage to find a solution for this issue ?
Thanks in advance

**Comment by william-ferguson-au** [comment]
@VinceGall no I didn't
