### ISSUE TITLE
Can't set/clear same environment variable bug or design intent?

### ISSUE THREAD

**Issue by bfett2005** [junit-pioneer/junit-pioneer#582]
Noticed this documentation here:
https://junit-pioneer.org/docs/environment-variables/

Note that class level configurations are overwritten by method level configurations:
```
@ClearEnvironmentVariable(key = "some variable")
class MyEnvironmentVariableTest {

    @Test
    @SetEnvironmentVariable(key = "some variable",
            value = "new value")
    void test() {
        assertThat(System.getenv("some variable"))
            .isEqualTo("new value");
    }
}
```

When attempting the same thing on a Java 8 unit test, the following exception is produced:
```
Don't clear/set the same entry more than once.
org.junit.jupiter.api.extension.ExtensionConfigurationException: Don't clear/set the same entry more than once.
	at org.junitpioneer.jupiter.AbstractEntryBasedExtension.clearAndSetEntries(AbstractEntryBasedExtension.java:101)
Caused by: java.lang.IllegalStateException: Cannot clear and set the following entries at the same time: 
	at org.junitpioneer.jupiter.AbstractEntryBasedExtension.lambda$preventClearAndSetSameEntries$1(AbstractEntryBasedExtension.java:120)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.junitpioneer.jupiter.AbstractEntryBasedExtension.preventClearAndSetSameEntries(AbstractEntryBasedExtension.java:119)
	at org.junitpioneer.jupiter.AbstractEntryBasedExtension.clearAndSetEntries(AbstractEntryBasedExtension.java:98)
	... 75 more
```

Just wondering is the documentation incorrect? I was hoping to use this functionality to set a common value and then clear it out for a single test and cut down on some duplication. Not a big deal if this is the design intent, just trying to understand if the documentation is correct or not.

**Comment by beatngu13** [comment]
This test doesn't fail (see checks/builds):

https://github.com/beatngu13/junit-pioneer/pull/8

You only get this exception if you clear and set an environment variable on the same container (e.g. test method).

Feel free to re-open if you run into this issue again. ✌️
