### ISSUE TITLE
JPMS: Pioneer does not contain module version

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#713]
@sormuras pointed out that we compile no module version version information into Pioneer's module

```
at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
     at org.junitpioneer/org.junitpioneer.jupiter.cartesian.ArgumentSets.add(ArgumentSets.java:50)
     at org.junitpioneer/org.junitpioneer.jupiter.cartesian.ArgumentSets.<init>(ArgumentSets.java:46)
     at org.junitpioneer/org.junitpioneer.jupiter.cartesian.ArgumentSets.argumentsForFirstParameter(ArgumentSets.java:73)
     at test.junit/test.junit.JUnitPioneerTests.test(JUnitPioneerTests.java:11)
     at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
     at java.base/java.lang.reflect.Method.invoke(Method.java:578)
     at org.junit.platform.commons@1.9.2/org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
     at org.junit.jupiter.engine@5.9.2/org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
```

"Just" need to pass `--module-version X` to `javac` or `jar` - similar to https://github.com/junit-team/junit5/blob/5b04c9492ab565f7a85bdf1789f7116f374a7a0d/buildSrc/src/main/kotlin/java-library-conventions.gradle.kts#L158

**Comment by Bukama** [comment]
Even that I gave it a try (see #716) I leave this open as I have no clue if my way is the correct one.

**Comment by aalmiray** [comment]
`options.javaModuleVersion` is a `Property<String>` added in Gradle 6.4
