### ISSUE TITLE
Add module version information

### ISSUE THREAD

**Issue by sormuras** [junit-pioneer/junit-pioneer#714]
From the stacktrace below ...
```
    at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
     at org.junitpioneer/org.junitpioneer.jupiter.cartesian.ArgumentSets.add(ArgumentSets.java:50)
     at org.junitpioneer/org.junitpioneer.jupiter.cartesian.ArgumentSets.<init>(ArgumentSets.java:46)
     at org.junitpioneer/org.junitpioneer.jupiter.cartesian.ArgumentSets.argumentsForFirstParameter(ArgumentSets.java:73)
     at test.junit/test.junit.JUnitPioneerTests.test(JUnitPioneerTests.java:11)
     at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
     at java.base/java.lang.reflect.Method.invoke(Method.java:578)
     at org.junit.platform.commons@1.9.2/org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
     at org.junit.jupiter.engine@5.9.2/org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
```
... one can see that JUnit Jupiter `5.9.2` and JUnit Platform `1.9.2` were loaded into the module graph when an exception was created.

It would be great if Pioneer would also include module version information in its compiled module descriptor.

**Comment by sormuras** [comment]
Duplicates #713
