### ISSUE TITLE
StdIo extension mishandles non-ASCII StdOut

### ISSUE THREAD

**Issue by J08nY** [junit-pioneer/junit-pioneer#822]
The following code is broken using Java 21.0.2 and junit-pioneer 2.2.0:

```java
    @Test
    @StdIo
    public void stdOutTest(StdOut out) {
        String s = "■━━━".repeat(100);
        System.out.println(s);
    }
```

```java
java.lang.IndexOutOfBoundsException: Range [0, 8190) out of bounds for length 2732

	at java.base/jdk.internal.util.Preconditions$3.apply(Preconditions.java:71)
	at java.base/jdk.internal.util.Preconditions$3.apply(Preconditions.java:68)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:684)
	at java.base/java.lang.StringBuffer.append(StringBuffer.java:393)
	at java.base/java.io.StringWriter.write(StringWriter.java:122)
	at org.junitpioneer.jupiter.StdOutputStream.write(StdOutputStream.java:33)
	at java.base/java.io.PrintStream.implWrite(PrintStream.java:643)
	at java.base/java.io.PrintStream.write(PrintStream.java:623)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:309)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:381)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:357)
	at java.base/sun.nio.cs.StreamEncoder.lockedWrite(StreamEncoder.java:158)
	at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:139)
	at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:219)
	at java.base/java.io.BufferedWriter.implFlushBuffer(BufferedWriter.java:178)
	at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:163)
	at java.base/java.io.PrintStream.implWriteln(PrintStream.java:848)
	at java.base/java.io.PrintStream.writeln(PrintStream.java:826)
	at java.base/java.io.PrintStream.println(PrintStream.java:1168)
	at stdOutTest(AppTests.java:46)
```

Basically, what I think is happening is that `StdOutputStream` is mishandling the bytes it is receiving:

https://github.com/junit-pioneer/junit-pioneer/blob/98cef28462c8b7ab66231cc5b7e8daef3b329f67/src/main/java/org/junitpioneer/jupiter/StdOutputStream.java#L32-L34

It takes a byte array and its length, then creates a String from it and passes the length unchanged to the StringWriter. However, as this is not ASCII byte array length does not equal String length and this then hits the out-out-bounds exception later.

**Comment by Michael1993** [comment]
Hi @J08nY! Unfortunately, I could not reproduce this issue. Could you create an example project with this bug?

**Comment by Michael1993** [comment]
Nevermind, I spoke too soon, I managed to reproduce it locally.
